USE StayWell;

DROP TABLE IF EXISTS SUMMER_SCHOOL_RENTALS;
CREATE TABLE SUMMER_SCHOOL_RENTALS (
    PROPERTY_ID NUMERIC,
    OFFICE_NUM NUMERIC,
    ADDRESS varchar(100),
    SQR_FT smallint,
    BDRMS smallint,
    FLOORS tinyint,
    WEEKLY_RENT smallint,
    OWNER_NUM char(5),
    PRIMARY KEY(PROPERTY_ID)
);

ALTER TABLE SUMMER_SCHOOL_RENTALS
DROP COLUMN BDRMS;

INSERT INTO SUMMER_SCHOOL_RENTALS (PROPERTY_ID, OFFICE_NUM, ADDRESS, SQR_FT, FLOORS, WEEKLY_RENT, OWNER_NUM)
VALUES(13, 1, '5867 Goodwin Ave', 1650, 1, 400, 'CO103');

DROP TABLE SUMMER_SCHOOL_RENTALS;

